// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `CountKnowledge`. */
interface ICountKnowledgeResult {
    total: number;
}

/** Result of query `CountPeople`. */
interface ICountPeopleResult {
    total: number | null;
}

/** Result of query `FindPeopleByIds`. */
interface IFindPeopleByIdsResult {
    id: string;
    name: string | null;
    email: string | null;
}

/** Result of query `FindPeopleByNameOrEmail`. */
interface IFindPeopleByNameOrEmailResult {
    id: string;
    name: string | null;
    email: string | null;
}

/** Result of query `UpdatePerson`. */
interface IUpdatePersonResult {
    id: string;
}

/** Result of query `SelectPeoplePage`. */
interface ISelectPeoplePageResult {
    id: string;
    name: string | null;
    email: string | null;
    is_external: boolean;
    data_sources: Array<{
        data_source_key: string;
        data_source_user_id: string;
    }>;
    records_count: number;
}

/** Result of query `CreateApiKey`. */
interface ICreateApiKeyResult {
    id: string;
    name: string;
    key_prefix: string;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    created_by: string;
}

/** Result of query `ListApiKeys`. */
interface IListApiKeysResult {
    id: string;
    name: string;
    key_prefix: string;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    created_by: string;
}

/** Result of query `ApiKeyExists`. */
interface IApiKeyExistsResult {
    exists: boolean | null;
}

/** Result of query `FindApiKeyCreatedBy`. */
interface IFindApiKeyCreatedByResult {
    created_by: string;
}

/** Result of query `UpdateApiKey`. */
interface IUpdateApiKeyResult {
    id: string;
    name: string;
    key_prefix: string;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    created_by: string;
}

/** Result of query `RemoveApiKey`. */
interface IRemoveApiKeyResult {
    id: string;
}

/** Result of query `CreateKnowledgeType`. */
interface ICreateKnowledgeTypeResult {
    id: string;
    name: string;
}

/** Result of query `ListKnowledgeTypes`. */
interface IListKnowledgeTypesResult {
    id: string;
    name: string;
}

/** Result of query `FindKnowledgeTypeById`. */
interface IFindKnowledgeTypeByIdResult {
    id: string;
    name: string;
}

/** Result of query `KnowledgeTypeNameTaken`. */
interface IKnowledgeTypeNameTakenResult {
    taken: boolean | null;
}

/** Result of query `UpdateKnowledgeType`. */
interface IUpdateKnowledgeTypeResult {
    id: string;
    name: string;
}

/** Result of query `KnowledgeTypeIsReferenced`. */
interface IKnowledgeTypeIsReferencedResult {
    referenced: boolean | null;
}

/** Result of query `RemoveKnowledgeType`. */
interface IRemoveKnowledgeTypeResult {
    id: string;
}

/** Result of query `UpsertDataSource`. */
interface IUpsertDataSourceResult {
    id: string;
}

/** Result of query `ListRecordSources`. */
interface IListRecordSourcesResult {
    data_source_id: string;
    data_source_key: string;
    count: number;
    oldest_created_at: Date;
    newest_created_at: Date;
    newest_updated_at: Date;
}

/** Result of query `CountRecords`. */
interface ICountRecordsResult {
    total: number;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults {
        CountKnowledge: ICountKnowledgeResult;
        CountPeople: ICountPeopleResult;
        FindPeopleByIds: IFindPeopleByIdsResult;
        FindPeopleByNameOrEmail: IFindPeopleByNameOrEmailResult;
        UpdatePerson: IUpdatePersonResult;
        SelectPeoplePage: ISelectPeoplePageResult;
        CreateApiKey: ICreateApiKeyResult;
        ListApiKeys: IListApiKeysResult;
        ApiKeyExists: IApiKeyExistsResult;
        FindApiKeyCreatedBy: IFindApiKeyCreatedByResult;
        UpdateApiKey: IUpdateApiKeyResult;
        RemoveApiKey: IRemoveApiKeyResult;
        CreateKnowledgeType: ICreateKnowledgeTypeResult;
        ListKnowledgeTypes: IListKnowledgeTypesResult;
        FindKnowledgeTypeById: IFindKnowledgeTypeByIdResult;
        KnowledgeTypeNameTaken: IKnowledgeTypeNameTakenResult;
        UpdateKnowledgeType: IUpdateKnowledgeTypeResult;
        KnowledgeTypeIsReferenced: IKnowledgeTypeIsReferencedResult;
        RemoveKnowledgeType: IRemoveKnowledgeTypeResult;
        UpsertDataSource: IUpsertDataSourceResult;
        ListRecordSources: IListRecordSourcesResult;
        CountRecords: ICountRecordsResult;
    }
}

export {};
