// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `CreateApiKey`. */
export interface ICreateApiKeyResult {
    id: string;
    name: string;
    key_prefix: string;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    created_by: string;
}

/** Result of query `ListApiKeys`. */
export interface IListApiKeysResult {
    id: string;
    name: string;
    key_prefix: string;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    created_by: string;
}

/** Result of query `ApiKeyExists`. */
export interface IApiKeyExistsResult {
    exists: boolean | null;
}

/** Result of query `FindApiKeyCreatedBy`. */
export interface IFindApiKeyCreatedByResult {
    created_by: string;
}

/** Result of query `UpdateApiKey`. */
export interface IUpdateApiKeyResult {
    id: string;
    name: string;
    key_prefix: string;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    created_by: string;
}

/** Result of query `RemoveApiKey`. */
export interface IRemoveApiKeyResult {
    id: string;
}

/** Result of query `CreateKnowledgeType`. */
export interface ICreateKnowledgeTypeResult {
    id: string;
    name: string;
}

/** Result of query `ListKnowledgeTypes`. */
export interface IListKnowledgeTypesResult {
    id: string;
    name: string;
}

/** Result of query `FindKnowledgeTypeById`. */
export interface IFindKnowledgeTypeByIdResult {
    id: string;
    name: string;
}

/** Result of query `KnowledgeTypeNameTaken`. */
export interface IKnowledgeTypeNameTakenResult {
    taken: boolean | null;
}

/** Result of query `UpdateKnowledgeType`. */
export interface IUpdateKnowledgeTypeResult {
    id: string;
    name: string;
}

/** Result of query `KnowledgeTypeIsReferenced`. */
export interface IKnowledgeTypeIsReferencedResult {
    referenced: boolean | null;
}

/** Result of query `RemoveKnowledgeType`. */
export interface IRemoveKnowledgeTypeResult {
    id: string;
}

/** Result of query `SearchKnowledgePreview`. */
export interface ISearchKnowledgePreviewResult {
    id: string;
    title: string;
}

/** Result of query `SearchKnowledgeFull`. */
export interface ISearchKnowledgeFullResult {
    id: string;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    title: string;
    body: string;
    knowledge_type_id: string;
    knowledge_type_name: string;
    score: number | null;
    snippet: string | null;
    participants: Array<import("#db/types.ts").Participant>;
    source_record_ids: string[];
}

/** Result of query `InsertKnowledge`. */
export interface IInsertKnowledgeResult {
    id: string;
}

/** Result of query `KnowledgeExists`. */
export interface IKnowledgeExistsResult {
    exists: boolean | null;
}

/** Result of query `DeleteKnowledge`. */
export interface IDeleteKnowledgeResult {
    id: string;
}

/** Result of query `SelectKnowledge`. */
export interface ISelectKnowledgeResult {
    id: string;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    title: string;
    body: string;
    knowledge_type_id: string;
    knowledge_type_name: string;
    participants: Array<import("#db/types.ts").Participant>;
    source_record_ids: string[];
}

/** Result of query `KnowledgeTypeExists`. */
export interface IKnowledgeTypeExistsResult {
    exists: boolean | null;
}

/** Result of query `SelectExistingPeopleIds`. */
export interface ISelectExistingPeopleIdsResult {
    id: string;
}

/** Result of query `SelectExistingRecordIds`. */
export interface ISelectExistingRecordIdsResult {
    id: string;
}

/** Result of query `CountKnowledge`. */
export interface ICountKnowledgeResult {
    total: number;
}

/** Result of query `CountPeople`. */
export interface ICountPeopleResult {
    total: number | null;
}

/** Result of query `FindPeopleByIds`. */
export interface IFindPeopleByIdsResult {
    id: string;
    name: string | null;
    email: string | null;
}

/** Result of query `FindPeopleByNameOrEmail`. */
export interface IFindPeopleByNameOrEmailResult {
    id: string;
    name: string | null;
    email: string | null;
}

/** Result of query `UpdatePerson`. */
export interface IUpdatePersonResult {
    id: string;
}

/** Result of query `ReassignPersonDataSources`. */
export interface IReassignPersonDataSourcesResult {
    id: string;
}

/** Result of query `ReassignPersonRecords`. */
export interface IReassignPersonRecordsResult {
    record_id: string;
}

/** Result of query `SelectPeoplePage`. */
export interface ISelectPeoplePageResult {
    id: string;
    name: string | null;
    email: string | null;
    is_external: boolean;
    data_sources: Array<{
        data_source_key: string;
        data_source_user_id: string;
    }>;
    records_count: number;
}

/** Result of query `UpsertDataSource`. */
export interface IUpsertDataSourceResult {
    id: string;
}

/** Result of query `ListRecordSources`. */
export interface IListRecordSourcesResult {
    data_source_id: string;
    data_source_key: string;
    count: number;
    oldest_created_at: Date;
    newest_created_at: Date;
    newest_updated_at: Date;
}

/** Result of query `SearchRecords`. */
export interface ISearchRecordsResult {
    id: string;
    data_source_id: string;
    data_source_key: string;
    created_at: Date;
    updated_at: Date;
    body: string;
    score: number | null;
    snippet: string | null;
    participants: Array<import("#db/types.ts").Participant>;
}

/** Result of query `CountRecords`. */
export interface ICountRecordsResult {
    total: number;
}

/** Result of query `GetRecord`. */
export interface IGetRecordResult {
    id: string;
    data_source_id: string;
    data_source_key: string;
    created_at: Date;
    updated_at: Date;
    body: string;
    participants: Array<import("#db/types.ts").Participant>;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults {
        CreateApiKey: ICreateApiKeyResult;
        ListApiKeys: IListApiKeysResult;
        ApiKeyExists: IApiKeyExistsResult;
        FindApiKeyCreatedBy: IFindApiKeyCreatedByResult;
        UpdateApiKey: IUpdateApiKeyResult;
        RemoveApiKey: IRemoveApiKeyResult;
        CreateKnowledgeType: ICreateKnowledgeTypeResult;
        ListKnowledgeTypes: IListKnowledgeTypesResult;
        FindKnowledgeTypeById: IFindKnowledgeTypeByIdResult;
        KnowledgeTypeNameTaken: IKnowledgeTypeNameTakenResult;
        UpdateKnowledgeType: IUpdateKnowledgeTypeResult;
        KnowledgeTypeIsReferenced: IKnowledgeTypeIsReferencedResult;
        RemoveKnowledgeType: IRemoveKnowledgeTypeResult;
        SearchKnowledgePreview: ISearchKnowledgePreviewResult;
        SearchKnowledgeFull: ISearchKnowledgeFullResult;
        InsertKnowledge: IInsertKnowledgeResult;
        KnowledgeExists: IKnowledgeExistsResult;
        DeleteKnowledge: IDeleteKnowledgeResult;
        SelectKnowledge: ISelectKnowledgeResult;
        KnowledgeTypeExists: IKnowledgeTypeExistsResult;
        SelectExistingPeopleIds: ISelectExistingPeopleIdsResult;
        SelectExistingRecordIds: ISelectExistingRecordIdsResult;
        CountKnowledge: ICountKnowledgeResult;
        CountPeople: ICountPeopleResult;
        FindPeopleByIds: IFindPeopleByIdsResult;
        FindPeopleByNameOrEmail: IFindPeopleByNameOrEmailResult;
        UpdatePerson: IUpdatePersonResult;
        ReassignPersonDataSources: IReassignPersonDataSourcesResult;
        ReassignPersonRecords: IReassignPersonRecordsResult;
        SelectPeoplePage: ISelectPeoplePageResult;
        UpsertDataSource: IUpsertDataSourceResult;
        ListRecordSources: IListRecordSourcesResult;
        SearchRecords: ISearchRecordsResult;
        CountRecords: ICountRecordsResult;
        GetRecord: IGetRecordResult;
    }
}

export {};
