/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as configureCmd } from './commands/configure.ts';
import type { command as daemonCmd } from './commands/daemon.ts';
import type { command as discoverCmd } from './commands/discover.ts';
import type { command as initCmd } from './commands/init.ts';
import type { command as installdaemonCmd } from './commands/install-daemon.ts';
import type { command as statusCmd } from './commands/status.ts';
import type { command as syncnowCmd } from './commands/sync-now.ts';
import type { command as uninstalldaemonCmd } from './commands/uninstall-daemon.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    configure: {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    daemon: {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    discover: {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    init: {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'install-daemon': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    status: {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'sync-now': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'uninstall-daemon': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    configure: {
      segment: { kind: 'literal', value: 'configure' },
      command: {
        path: 'configure',
        load: () => import('./commands/configure.ts').then((m) => m.command),
      },
      literalChildren: {},
      paramChild: null,
    },
    daemon: {
      segment: { kind: 'literal', value: 'daemon' },
      command: {
        path: 'daemon',
        load: () => import('./commands/daemon.ts').then((m) => m.command),
      },
      literalChildren: {},
      paramChild: null,
    },
    discover: {
      segment: { kind: 'literal', value: 'discover' },
      command: {
        path: 'discover',
        load: () => import('./commands/discover.ts').then((m) => m.command),
      },
      literalChildren: {},
      paramChild: null,
    },
    init: {
      segment: { kind: 'literal', value: 'init' },
      command: { path: 'init', load: () => import('./commands/init.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'install-daemon': {
      segment: { kind: 'literal', value: 'install-daemon' },
      command: {
        path: 'install-daemon',
        load: () => import('./commands/install-daemon.ts').then((m) => m.command),
      },
      literalChildren: {},
      paramChild: null,
    },
    status: {
      segment: { kind: 'literal', value: 'status' },
      command: {
        path: 'status',
        load: () => import('./commands/status.ts').then((m) => m.command),
      },
      literalChildren: {},
      paramChild: null,
    },
    'sync-now': {
      segment: { kind: 'literal', value: 'sync-now' },
      command: {
        path: 'sync-now',
        load: () => import('./commands/sync-now.ts').then((m) => m.command),
      },
      literalChildren: {},
      paramChild: null,
    },
    'uninstall-daemon': {
      segment: { kind: 'literal', value: 'uninstall-daemon' },
      command: {
        path: 'uninstall-daemon',
        load: () => import('./commands/uninstall-daemon.ts').then((m) => m.command),
      },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
