/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as cloudAddIntegrationsCmd } from './commands/cloud/add/integrations.ts';
import type { command as cloudAddSyncsCmd } from './commands/cloud/add/syncs.ts';
import type { command as cloudDaemonAgentsyncCmd } from './commands/cloud/daemon/agent-sync.ts';
import type { command as cloudDestroyCmd } from './commands/cloud/destroy.ts';
import type { command as cloudDoctorCmd } from './commands/cloud/doctor.ts';
import type { command as cloudInstallAgentsyncCmd } from './commands/cloud/install/agent-sync.ts';
import type { command as cloudResumeCmd } from './commands/cloud/resume.ts';
import type { command as cloudSetupCmd } from './commands/cloud/setup.ts';
import type { command as cloudStatusAgentsyncCmd } from './commands/cloud/status/agent-sync.ts';
import type { command as cloudSyncnowAgentsyncCmd } from './commands/cloud/sync-now/agent-sync.ts';
import type { command as cloudUninstallAgentsyncCmd } from './commands/cloud/uninstall/agent-sync.ts';
import type { command as cloudUpdateCmd } from './commands/cloud/update.ts';
import type { command as localAddIntegrationsCmd } from './commands/local/add/integrations.ts';
import type { command as localAddSyncsCmd } from './commands/local/add/syncs.ts';
import type { command as localDaemonAgentsyncCmd } from './commands/local/daemon/agent-sync.ts';
import type { command as localDestroyCmd } from './commands/local/destroy.ts';
import type { command as localDoctorCmd } from './commands/local/doctor.ts';
import type { command as localInstallAgentsyncCmd } from './commands/local/install/agent-sync.ts';
import type { command as localResumeCmd } from './commands/local/resume.ts';
import type { command as localSetupCmd } from './commands/local/setup.ts';
import type { command as localStatusAgentsyncCmd } from './commands/local/status/agent-sync.ts';
import type { command as localSyncnowAgentsyncCmd } from './commands/local/sync-now/agent-sync.ts';
import type { command as localUninstallAgentsyncCmd } from './commands/local/uninstall/agent-sync.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'cloud add integrations': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud add syncs': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud daemon agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud destroy': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud doctor': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud install agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud resume': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud setup': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud status agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud sync-now agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud uninstall agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud update': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local add integrations': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local add syncs': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local daemon agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local destroy': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local doctor': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local install agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local resume': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local setup': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local status agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local sync-now agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local uninstall agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    cloud: {
      segment: { kind: 'literal', value: 'cloud' },
      command: null,
      literalChildren: {
        add: {
          segment: { kind: 'literal', value: 'add' },
          command: null,
          literalChildren: {
            integrations: {
              segment: { kind: 'literal', value: 'integrations' },
              command: {
                path: 'cloud add integrations',
                load: () => import('./commands/cloud/add/integrations.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            syncs: {
              segment: { kind: 'literal', value: 'syncs' },
              command: {
                path: 'cloud add syncs',
                load: () => import('./commands/cloud/add/syncs.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        daemon: {
          segment: { kind: 'literal', value: 'daemon' },
          command: null,
          literalChildren: {
            'agent-sync': {
              segment: { kind: 'literal', value: 'agent-sync' },
              command: {
                path: 'cloud daemon agent-sync',
                load: () => import('./commands/cloud/daemon/agent-sync.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        destroy: {
          segment: { kind: 'literal', value: 'destroy' },
          command: {
            path: 'cloud destroy',
            load: () => import('./commands/cloud/destroy.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        doctor: {
          segment: { kind: 'literal', value: 'doctor' },
          command: {
            path: 'cloud doctor',
            load: () => import('./commands/cloud/doctor.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        install: {
          segment: { kind: 'literal', value: 'install' },
          command: null,
          literalChildren: {
            'agent-sync': {
              segment: { kind: 'literal', value: 'agent-sync' },
              command: {
                path: 'cloud install agent-sync',
                load: () => import('./commands/cloud/install/agent-sync.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        resume: {
          segment: { kind: 'literal', value: 'resume' },
          command: {
            path: 'cloud resume',
            load: () => import('./commands/cloud/resume.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        setup: {
          segment: { kind: 'literal', value: 'setup' },
          command: {
            path: 'cloud setup',
            load: () => import('./commands/cloud/setup.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        status: {
          segment: { kind: 'literal', value: 'status' },
          command: null,
          literalChildren: {
            'agent-sync': {
              segment: { kind: 'literal', value: 'agent-sync' },
              command: {
                path: 'cloud status agent-sync',
                load: () => import('./commands/cloud/status/agent-sync.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        'sync-now': {
          segment: { kind: 'literal', value: 'sync-now' },
          command: null,
          literalChildren: {
            'agent-sync': {
              segment: { kind: 'literal', value: 'agent-sync' },
              command: {
                path: 'cloud sync-now agent-sync',
                load: () =>
                  import('./commands/cloud/sync-now/agent-sync.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        uninstall: {
          segment: { kind: 'literal', value: 'uninstall' },
          command: null,
          literalChildren: {
            'agent-sync': {
              segment: { kind: 'literal', value: 'agent-sync' },
              command: {
                path: 'cloud uninstall agent-sync',
                load: () =>
                  import('./commands/cloud/uninstall/agent-sync.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        update: {
          segment: { kind: 'literal', value: 'update' },
          command: {
            path: 'cloud update',
            load: () => import('./commands/cloud/update.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
    local: {
      segment: { kind: 'literal', value: 'local' },
      command: null,
      literalChildren: {
        add: {
          segment: { kind: 'literal', value: 'add' },
          command: null,
          literalChildren: {
            integrations: {
              segment: { kind: 'literal', value: 'integrations' },
              command: {
                path: 'local add integrations',
                load: () => import('./commands/local/add/integrations.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            syncs: {
              segment: { kind: 'literal', value: 'syncs' },
              command: {
                path: 'local add syncs',
                load: () => import('./commands/local/add/syncs.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        daemon: {
          segment: { kind: 'literal', value: 'daemon' },
          command: null,
          literalChildren: {
            'agent-sync': {
              segment: { kind: 'literal', value: 'agent-sync' },
              command: {
                path: 'local daemon agent-sync',
                load: () => import('./commands/local/daemon/agent-sync.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        destroy: {
          segment: { kind: 'literal', value: 'destroy' },
          command: {
            path: 'local destroy',
            load: () => import('./commands/local/destroy.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        doctor: {
          segment: { kind: 'literal', value: 'doctor' },
          command: {
            path: 'local doctor',
            load: () => import('./commands/local/doctor.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        install: {
          segment: { kind: 'literal', value: 'install' },
          command: null,
          literalChildren: {
            'agent-sync': {
              segment: { kind: 'literal', value: 'agent-sync' },
              command: {
                path: 'local install agent-sync',
                load: () => import('./commands/local/install/agent-sync.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        resume: {
          segment: { kind: 'literal', value: 'resume' },
          command: {
            path: 'local resume',
            load: () => import('./commands/local/resume.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        setup: {
          segment: { kind: 'literal', value: 'setup' },
          command: {
            path: 'local setup',
            load: () => import('./commands/local/setup.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        status: {
          segment: { kind: 'literal', value: 'status' },
          command: null,
          literalChildren: {
            'agent-sync': {
              segment: { kind: 'literal', value: 'agent-sync' },
              command: {
                path: 'local status agent-sync',
                load: () => import('./commands/local/status/agent-sync.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        'sync-now': {
          segment: { kind: 'literal', value: 'sync-now' },
          command: null,
          literalChildren: {
            'agent-sync': {
              segment: { kind: 'literal', value: 'agent-sync' },
              command: {
                path: 'local sync-now agent-sync',
                load: () =>
                  import('./commands/local/sync-now/agent-sync.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        uninstall: {
          segment: { kind: 'literal', value: 'uninstall' },
          command: null,
          literalChildren: {
            'agent-sync': {
              segment: { kind: 'literal', value: 'agent-sync' },
              command: {
                path: 'local uninstall agent-sync',
                load: () =>
                  import('./commands/local/uninstall/agent-sync.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
      },
      paramChild: null,
    },
  },
  paramChild: null,
};
