/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as cloudAddIntegrationsCmd } from './commands/cloud/add/integrations.ts';
import type { command as cloudAddSyncsCmd } from './commands/cloud/add/syncs.ts';
import type { command as cloudAgentsyncInstallCmd } from './commands/cloud/agent-sync/install.ts';
import type { command as cloudAgentsyncStatusCmd } from './commands/cloud/agent-sync/status.ts';
import type { command as cloudAgentsyncSyncnowCmd } from './commands/cloud/agent-sync/sync-now.ts';
import type { command as cloudAgentsyncUninstallCmd } from './commands/cloud/agent-sync/uninstall.ts';
import type { command as cloudDestroyCmd } from './commands/cloud/destroy.ts';
import type { command as cloudDoctorCmd } from './commands/cloud/doctor.ts';
import type { command as cloudResumeCmd } from './commands/cloud/resume.ts';
import type { command as cloudSetupCmd } from './commands/cloud/setup.ts';
import type { command as cloudUpdateCmd } from './commands/cloud/update.ts';
import type { command as localAddIntegrationsCmd } from './commands/local/add/integrations.ts';
import type { command as localAddSyncsCmd } from './commands/local/add/syncs.ts';
import type { command as localAgentsyncInstallCmd } from './commands/local/agent-sync/install.ts';
import type { command as localAgentsyncStatusCmd } from './commands/local/agent-sync/status.ts';
import type { command as localAgentsyncSyncnowCmd } from './commands/local/agent-sync/sync-now.ts';
import type { command as localAgentsyncUninstallCmd } from './commands/local/agent-sync/uninstall.ts';
import type { command as localDestroyCmd } from './commands/local/destroy.ts';
import type { command as localDoctorCmd } from './commands/local/doctor.ts';
import type { command as localResumeCmd } from './commands/local/resume.ts';
import type { command as localSetupCmd } from './commands/local/setup.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'cloud add integrations': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud add syncs': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud agent-sync install': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud agent-sync status': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud agent-sync sync-now': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud agent-sync uninstall': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud destroy': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud doctor': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud resume': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud setup': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud update': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local add integrations': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local add syncs': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local agent-sync install': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local agent-sync status': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local agent-sync sync-now': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local agent-sync uninstall': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local destroy': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local doctor': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local resume': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local setup': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    cloud: {
      segment: { kind: 'literal', value: 'cloud' },
      command: null,
      literalChildren: {
        add: {
          segment: { kind: 'literal', value: 'add' },
          command: null,
          literalChildren: {
            integrations: {
              segment: { kind: 'literal', value: 'integrations' },
              command: {
                path: 'cloud add integrations',
                load: () => import('./commands/cloud/add/integrations.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            syncs: {
              segment: { kind: 'literal', value: 'syncs' },
              command: {
                path: 'cloud add syncs',
                load: () => import('./commands/cloud/add/syncs.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        'agent-sync': {
          segment: { kind: 'literal', value: 'agent-sync' },
          command: null,
          literalChildren: {
            install: {
              segment: { kind: 'literal', value: 'install' },
              command: {
                path: 'cloud agent-sync install',
                load: () => import('./commands/cloud/agent-sync/install.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            status: {
              segment: { kind: 'literal', value: 'status' },
              command: {
                path: 'cloud agent-sync status',
                load: () => import('./commands/cloud/agent-sync/status.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            'sync-now': {
              segment: { kind: 'literal', value: 'sync-now' },
              command: {
                path: 'cloud agent-sync sync-now',
                load: () =>
                  import('./commands/cloud/agent-sync/sync-now.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            uninstall: {
              segment: { kind: 'literal', value: 'uninstall' },
              command: {
                path: 'cloud agent-sync uninstall',
                load: () =>
                  import('./commands/cloud/agent-sync/uninstall.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        destroy: {
          segment: { kind: 'literal', value: 'destroy' },
          command: {
            path: 'cloud destroy',
            load: () => import('./commands/cloud/destroy.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        doctor: {
          segment: { kind: 'literal', value: 'doctor' },
          command: {
            path: 'cloud doctor',
            load: () => import('./commands/cloud/doctor.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        resume: {
          segment: { kind: 'literal', value: 'resume' },
          command: {
            path: 'cloud resume',
            load: () => import('./commands/cloud/resume.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        setup: {
          segment: { kind: 'literal', value: 'setup' },
          command: {
            path: 'cloud setup',
            load: () => import('./commands/cloud/setup.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        update: {
          segment: { kind: 'literal', value: 'update' },
          command: {
            path: 'cloud update',
            load: () => import('./commands/cloud/update.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
    local: {
      segment: { kind: 'literal', value: 'local' },
      command: null,
      literalChildren: {
        add: {
          segment: { kind: 'literal', value: 'add' },
          command: null,
          literalChildren: {
            integrations: {
              segment: { kind: 'literal', value: 'integrations' },
              command: {
                path: 'local add integrations',
                load: () => import('./commands/local/add/integrations.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            syncs: {
              segment: { kind: 'literal', value: 'syncs' },
              command: {
                path: 'local add syncs',
                load: () => import('./commands/local/add/syncs.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        'agent-sync': {
          segment: { kind: 'literal', value: 'agent-sync' },
          command: null,
          literalChildren: {
            install: {
              segment: { kind: 'literal', value: 'install' },
              command: {
                path: 'local agent-sync install',
                load: () => import('./commands/local/agent-sync/install.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            status: {
              segment: { kind: 'literal', value: 'status' },
              command: {
                path: 'local agent-sync status',
                load: () => import('./commands/local/agent-sync/status.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            'sync-now': {
              segment: { kind: 'literal', value: 'sync-now' },
              command: {
                path: 'local agent-sync sync-now',
                load: () =>
                  import('./commands/local/agent-sync/sync-now.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            uninstall: {
              segment: { kind: 'literal', value: 'uninstall' },
              command: {
                path: 'local agent-sync uninstall',
                load: () =>
                  import('./commands/local/agent-sync/uninstall.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        destroy: {
          segment: { kind: 'literal', value: 'destroy' },
          command: {
            path: 'local destroy',
            load: () => import('./commands/local/destroy.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        doctor: {
          segment: { kind: 'literal', value: 'doctor' },
          command: {
            path: 'local doctor',
            load: () => import('./commands/local/doctor.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        resume: {
          segment: { kind: 'literal', value: 'resume' },
          command: {
            path: 'local resume',
            load: () => import('./commands/local/resume.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        setup: {
          segment: { kind: 'literal', value: 'setup' },
          command: {
            path: 'local setup',
            load: () => import('./commands/local/setup.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
  },
  paramChild: null,
};
