/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as deployAddIntegrationsCmd } from './commands/deploy/add/integrations.ts';
import type { command as deployAddSyncsCmd } from './commands/deploy/add/syncs.ts';
import type { command as deployDestroyCmd } from './commands/deploy/destroy.ts';
import type { command as deployDoctorCmd } from './commands/deploy/doctor.ts';
import type { command as deployResumeCmd } from './commands/deploy/resume.ts';
import type { command as deploySetupCmd } from './commands/deploy/setup.ts';
import type { command as deployUpdateCmd } from './commands/deploy/update.ts';
import type { command as localAddIntegrationsCmd } from './commands/local/add/integrations.ts';
import type { command as localAddSyncsCmd } from './commands/local/add/syncs.ts';
import type { command as localDestroyCmd } from './commands/local/destroy.ts';
import type { command as localDoctorCmd } from './commands/local/doctor.ts';
import type { command as localSetupCmd } from './commands/local/setup.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'deploy add integrations': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'deploy add syncs': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'deploy destroy': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'deploy doctor': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'deploy resume': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'deploy setup': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'deploy update': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local add integrations': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local add syncs': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local destroy': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local doctor': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local setup': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    deploy: {
      segment: { kind: 'literal', value: 'deploy' },
      command: null,
      literalChildren: {
        add: {
          segment: { kind: 'literal', value: 'add' },
          command: null,
          literalChildren: {
            integrations: {
              segment: { kind: 'literal', value: 'integrations' },
              command: {
                path: 'deploy add integrations',
                load: () => import('./commands/deploy/add/integrations.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            syncs: {
              segment: { kind: 'literal', value: 'syncs' },
              command: {
                path: 'deploy add syncs',
                load: () => import('./commands/deploy/add/syncs.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        destroy: {
          segment: { kind: 'literal', value: 'destroy' },
          command: {
            path: 'deploy destroy',
            load: () => import('./commands/deploy/destroy.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        doctor: {
          segment: { kind: 'literal', value: 'doctor' },
          command: {
            path: 'deploy doctor',
            load: () => import('./commands/deploy/doctor.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        resume: {
          segment: { kind: 'literal', value: 'resume' },
          command: {
            path: 'deploy resume',
            load: () => import('./commands/deploy/resume.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        setup: {
          segment: { kind: 'literal', value: 'setup' },
          command: {
            path: 'deploy setup',
            load: () => import('./commands/deploy/setup.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        update: {
          segment: { kind: 'literal', value: 'update' },
          command: {
            path: 'deploy update',
            load: () => import('./commands/deploy/update.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
    local: {
      segment: { kind: 'literal', value: 'local' },
      command: null,
      literalChildren: {
        add: {
          segment: { kind: 'literal', value: 'add' },
          command: null,
          literalChildren: {
            integrations: {
              segment: { kind: 'literal', value: 'integrations' },
              command: {
                path: 'local add integrations',
                load: () => import('./commands/local/add/integrations.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
            syncs: {
              segment: { kind: 'literal', value: 'syncs' },
              command: {
                path: 'local add syncs',
                load: () => import('./commands/local/add/syncs.ts').then((m) => m.command),
              },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        destroy: {
          segment: { kind: 'literal', value: 'destroy' },
          command: {
            path: 'local destroy',
            load: () => import('./commands/local/destroy.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        doctor: {
          segment: { kind: 'literal', value: 'doctor' },
          command: {
            path: 'local doctor',
            load: () => import('./commands/local/doctor.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
        setup: {
          segment: { kind: 'literal', value: 'setup' },
          command: {
            path: 'local setup',
            load: () => import('./commands/local/setup.ts').then((m) => m.command),
          },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
  },
  paramChild: null,
};
