name: tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: ./.github/actions/prepare

      - name: Run tests
        run: bun run test
